[local]
localhost

[local:vars]
IMG_ID="ami-0f3caa1cf4417e51b"
SSH_KEY="ptarunsam2air250326"
SG="sg-0f251de558141c602"
INST_TYPE="t3.micro"
INST_NAMES='["mongodb","catalogue","frontend","redis","user","cart","mysql","shipping","rabbitmq","payment","dispatch"]'