- name: "Installing MariaDB into the database"
  hosts: role___db_
  tasks:
  - name: "echo hi"
    ansible.builtin.debug:
      msg: "Hello"
  - name: "Install MariaDB"
    become: true
    ansible.builtin.package:
      name: mariadb114-server
      state: installed
    register: install_output
  - name: "Status check"
    ansible.builtin.debug:
      msg: "{{ install_output }}"