- name: "Installing and Configuring Nginx"
  hosts: "role__fe_"
  connection: ssh
  tasks:
  - name: "Install Nginx"
    become: true
    ansible.builtin.package:
      name: nginx
      state: present
  - name: "Delete Boilerplate code of nginx"
    ansible.builtin.file:
      path: "/usr/share/nginx/html/*"
      state: absent
  - name: "Downloading Scripts"
    ansible.builtin.get_url:
      url: "https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip"
      dest: "/tmp/frontend.zip"
  - name: "Unzip the Scripts"
    become: true
    ansible.builtin.unarchive:
      remote_src: yes
      src: "/tmp/frontend.zip"
      dest: "/usr/share/nginx/html/"
  - name: "Deploy frontend service file"
    become: true
    ansible.builtin.template:
      src: "nginx.conf.j2"
      dest: "/etc/nginx/nginx.conf"
  - name: "nginx service start"
    become: true
    ansible.builtin.service:  
      name: nginx
      enabled: yes
      state: started
      daemon-reload: yes
