- name: "Installing MariaDB into the database"
  hosts: role___db_
  tasks:
  - name: "echo hi"
    ansible.builtin.debug:
      msg: "Hello"
  - name: "Creating repo for MongoDB"
    ansible.builtin.copy:
      src: "~/roles/mongodb/mongo.repo"
      dest: /etc/yum.repos.d/mongo.repo
  - name: "Install MongoDB"
    become: true
    ansible.builtin.package:
      name: mongodb-org
      state: present
    register: install_output
  - name: "Status check"
    ansible.builtin.debug:
      msg: "{{ install_output }}"