- name: "Installing MariaDB into the database"
  hosts: role___db_
  tasks:
  - name: "echo hi"
    ansible.builtin.debug:
      msg: "Hello"
  - name: "Creating repo for MongoDB"
    become: true
    ansible.builtin.copy:
      src: "~/ansible-practise/roles/mongodb/mongo.repo"
      dest: /etc/yum.repos.d/mongo.repo
  - name: "Install MongoDB"
    become: true
    ansible.builtin.package:
      name: mongodb-org
      state: present
    register: install_output
  - name: "Status check"
    ansible.builtin.debug:
      msg: "{{ install_output }}"
  - name: "mongodb service start"
    become: true
    ansible.builtin.service:  
      name: mongod
      enabled: yes
      state: started
  - name: "Make Changes in mongodb configuration"
    become: true
    ansible.builtin.lineinfile:
      path: /etc/mongod.conf
      regexp: '^\s*bindIp:\s*127\.0\.0\.1'
      line: "  bindIp: 0.0.0.0"
