- name: "Executing ALL Playbooks"
  hosts: local
  connection: local
  tasks:
  - ansible.builtin.import_playbook: playbooks/provision.yaml
  - ansible.builtin.import_playbook: roles/mongodb/mongodb.yaml
  - ansible.builtin.import_playbook: roles/catalogue/catalogue.yaml
  - ansible.builtin.import_playbook: roles/frontend/frontend.yaml