- name: "Provisioning the EC2 Instances and relevant tagging"
  hosts: local
  connection: local
  tasks:
  - name: "Provisioning the EC2 Instances"
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      key_name: "{{ SSH_KEY }}"
      instance_type: "{{ INST_TYPE }}"
      security_group: "{{ SG }}"
      image_id: "{{ IMG_ID }}"
    register: "ec2_output"
    loop: "{{ INST_NAMES }}"
  - name: "Getting Basic Details of Instance names and Instance Ids"
    set_fact:
      instance_names: "{{ ec2_output.results | map(attribute='item') | list }}"
      instance_ids: "{{ ec2_output.results | map(attribute='instance_ids') | map('first') | list }}"
      private_ip_address: "{{ ec2_output.results | map(attribute='instances') | map('first') | map(attribute='private_ip_address') | list }}"
  - name: "Mapping Details into dict"
    set_fact:
      instance_map: "{{ dict(instance_ids | zip(instance_names | zip(private_ip_address))) }}"
  - name: "Print outputs for understanding"
    ansible.builtin.debug:
      msg: "{{ item.key }}"
    loop: "{{ instance_map | dict2items }}"
  - name: "Tagging EC2 Instances"
    amazon.aws.ec2_tag:
      region: us-east-1
      resource: "{{ item.key }}"
      state: present
      tags:
        Role: |
          {% if "mongodb" in item.key %}
          mg
          {% elif "catalogue" in item.key %}
          cl
          {% elif "frontend" in item.key %}
          fe
          {% elif "redis" in item.key %}
          re
          {% elif "user" in item.key %}
          us
          {% elif "cart" in item.key %}
          ca
          {% elif "mysql" in item.key %}
          my
          {% elif "shipping" in item.key %}
          shi
          {% elif "rabbitmq" in item.key %}
          rb
          {% elif "payment" in item.key %}
          py
          {% elif "dispatch" in item.key %}
          di
          {% else %}
          unknown
          {% endif %}
    loop: "{{ instance_map | dict2items }}"
  # - name: "Assign Service IPs"
  #   set_fact:
  #     "{{ item.}}"