- name: "Provisioning the EC2 Instances and relevant tagging"
  hosts: local
  connection: local
  tasks:
  - name: "Provisioning the EC2 Instances"
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      key_name: "{{ SSH_KEY }}"
      instance_type: "{{ INST_TYPE }}"
      security_group: "{{ SG }}"
      image_id: "{{ IMG_ID }}"
    register: "ec2_output"
    loop: "{{ INST_NAMES }}"
  - name: "Getting Basic Details of Instance names and Instance Ids"
    set_fact:
      instance_names: "{{ ec2_output.results | map(attribute='item') | list }}"
      instance_ids: "{{ ec2_output.results | map(attribute='instance_ids') | map('first') | list }}"
  - name: "Mapping Details into dict"
    set_fact:
      instance_map: "{{ dict(instance_ids | zip(instance_names)) }}"
  - name: "Print outputs for understanding"
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ instance_map.keys() }}" 
  - name: "Tagging EC2 Instances"
    amazon.aws.ec2_tag:
      region: us-east-1
      resource: "{{ item }}"
      state: present
      tags:
        Role: |
          {% if "database" in instance_map[item] %}
          db
          {% elif "frontend" in instance_map[item] %}
          fe
          {% elif "backend" in instance_map[item] %}
          be
          {% else %}
          unknown
          {% endif %}
    loop: "{{ instance_map.keys() }}"
