mongodb_ip: "{{ mongodb_ip_sf}}"
catalogue: "{{ catalogue_ip_sf}}"
frontend: "{{ frontend_ip_sf}}"
redis: "{{ redis_ip_sf}}"
user: "{{ user_ip_sf}}"
cart: "{{ cart_ip_sf}}"
mysql: "{{ mysql_ip_sf}}"
shipping: "{{ shipping_ip_sf}}"
rabbitmq: "{{ rabbitmq_ip_sf}}"
payment: "{{ payment_ip_sf}}"
dispatch: "{{ dispatch_ip_sf}}"